name:                grid-proto
version:             0.1.0.0
synopsis:            Grid-based prototyping framework
description:         Grid-based prototyping framework. Useful for games.
homepage:            https://github.com/jxv/grid-proto#readme
license:             BSD3
author:              Joe Vargas
maintainer:          joevargas92@gmail.com
copyright:           2019 Joe Vargas
category:            Game
extra-source-files:
- README.md

flags:
  examples:
    manual: true
    default: false

dependencies:
  - aeson >= 1.4
  - base >= 4.7 && < 5
  - bytestring
  - sdl2 >= 2.4.0
  - sdl2-gfx
  - sdl2-ttf
  - sdl2-fps
  - sdl2-mixer
  - StateVar
  - containers >= 0.6
  - linear
  - text >= 1.2.3
  - vector >= 0.12

library:
  exposed-modules:
    - GridProto.Core
    - GridProto.Classic
  source-dirs: src

executables:
  board-example:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/board
    main: Main.hs
    dependencies:
      - grid-proto
  text-example:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/text
    main: Main.hs
    dependencies:
      - grid-proto
  arrows-example:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/arrows
    main: Main.hs
    dependencies:
      - grid-proto
  controller-example:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/controller
    main: Main.hs
    dependencies:
      - grid-proto
  sound-example:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/sound
    main: Main.hs
    dependencies:
      - grid-proto
  tactics:
    when:
      condition: flag(examples)
      buildable: true
    source-dirs: examples/tactics
    main: Main.hs
    dependencies:
      - grid-proto


